name: Depression Prediction CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Test Model Training
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] pandas scikit-learn jinja2 python-multipart mlflow

      - name: Start MLflow tracking server
        run: |
          mkdir -p mlruns
          nohup mlflow server \
            --backend-store-uri ./mlruns \
            --default-artifact-root ./mlruns \
            --host 127.0.0.1 \
            --port 5000 > mlflow.log 2>&1 &
          sleep 10  # wait for MLflow server to start

      - name: Run full pipeline (train & save model)
        run: |
          python src/model_building.py

      - name: Check if model exists
        run: |
          if [ ! -f models/SVC.pkl ]; then
            echo "❌ Model file not found!"
            exit 1
          fi

  build_and_push:
    name: 🏗️ Build & 🚀 Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/depression-prediction:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/depression-prediction:latest

