name: Depression Prediction CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Test Model Training
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn[standard] pandas scikit-learn jinja2 python-multipart

    - name: Run full pipeline (train & save model)
      run: |
        python src/model_building.py

    - name: Check if model exists
      run: |
        if [ ! -f models/SVC.pkl ]; then
          echo "❌ Model file not found!"
          exit 1
        fi

  build:
    name: 🏗️ Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/depression-prediction:latest .

  push:
    name: 🚀 Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/depression-prediction:latest
